### ISSUE TITLE
Include sample numbers

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/cohort-gene#10]
I enter cohort.iobio and have variants for all probands, and variants for my subset. It would be good to have a brief summary of the number of samples. We already have labels for the filter applied to generate the subset, so maybe we add one of these labels to both variant panels to show how many samples are in each set.

**Comment by stefinfection** [comment]
![Screen Shot 2018-03-30 at 11.15.27 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68fe261aa094001167db93/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206457f36b7191a379ee0c2a54415d49bc30254d58eeb9cb74fce36f34985619e8803f0d22c43b12ffbb814be903ba20894a86bebd8848c4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e34956a4123267e670336e0a.png)

**Comment by stefinfection** [comment]
Put in a 'n = x' chip right after the Probands chip - can move anywhere relative to other chips, if we prefer it before or after the filters
