### ISSUE TITLE
Displaying variants with no defined impact

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/cohort-gene#17]
Go to gene CHD8, there are a load of upstream variants that have no VEP impact. Do we want to remove these as well?

**Comment by stefinfection** [comment]
I removed the ones without the VEP call. We could possibly include variants with a low impact as well - the modifier ones are the large group causing problems...

**Comment by AlistairNWard** [comment]
I'm fine either way. Ultimately, we will give the user the option to filter, so for now, I think this is good.
