### ISSUE TITLE
Authentication / Authorization

### ISSUE THREAD

**Issue by chmille4** [iobio/cohort-gene#32]
1) Remove access code from header
Should remove access_code from url so that a user doesn't accidentally send the url to someone, which would give them full access to the original users account.  Can look at bam.iobio.io to see how to do this with local storage - https://github.com/chmille4/bam.iobio.io/blob/gh-pages/index.html#L877

 2) Setup oauth reauthorization when there's a timeout

Check out bam.iobio for how we are doing this: https://github.com/chmille4/bam.iobio.io/blob/gh-pages/index.html#L930

**Comment by stefinfection** [comment]
Oauth and vue hash routing don't working nicely together - have to parse query params independently or configure routing using history mode
