### ISSUE TITLE
Users upload their own VCF data

### ISSUE THREAD

**Issue by stefinfection** [iobio/cohort-gene#42]

**Comment by stefinfection** [comment]
Will this always be in conjunction with the display of the Simons data? Or do we also want a stand alone application that can compare two different sets of samples in only the user VCF?

**Comment by AlistairNWard** [comment]
My opinion would be that it is always in conjunction with the Simons data (assuming they've come through the SFARI data from hub). We could then use a colour scheme to identify the variants in the users data?
